version: '3.4'

services:
  loyalty-card:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      ENV: dev
    ports:
      - $REST_PORT:$REST_PORT
    volumes:
      - .:/go/src/
    networks:
      - loyalty-card
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  pgadmin:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    networks:
      - loyalty-card

networks:
  loyalty-card:
    driver: bridge
