apiVersion: v1
kind: Service
metadata:
  name: loyalty-card
  labels:
    app: loyalty-card
    service: loyalty-card
spec:
  type: ClusterIP
  selector:
    app: loyalty-card
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
